server:
  port: 8000

spring:
  application:
    name: gateway-service


  cloud:
    gateway:
      routes:
        - id: employee-service
          uri:
            lb://employee-service
          predicates:
            - Path=/employee/**